export const POST_ARTICLE_START = 'POST_ARTICLE_START';
export const POST_ARTICLE_SUCCESS = 'POST_ARTICLE_SUCCESS';
export const POST_ARTICLE_FAIL = 'POST_ARTICLE_FAIL';
export const POST_ARTICLE_INIT = 'POST_ARTICLE_INIT';